export const cachedData = {
  "tdid": "t_4SdA_8344",
  "createTime": 1660050578,
  "updateTime": 1660080385717,
  "status": 40,
  "ad": 1,
  "title": "MPB Darts Liga 8. Kolo 9. sezona",
  "t_date": 0,
  "s_date": 1660050578,
  "details": "8.Kolo, letn\u00e1 sez\u00f3na",
  "image": "https://mpbdarts-club.sk/images/logo.png",
  "color": "#ffffff",
  "chat": 0,
  "show_avg": 1,
  "auto_complete": 1,
  "game_type": 5,
  "individual_pass": 0,
  "hide_sns": 0,
  "common_join": 1,
  "show_entry_no": 0,
  "rr_setting": {
    "round_robin": 1,
    "robin_count": 8,
    "robin_player_count": 6,
    "show_order": 1,
    "limit": 1,
    "limit_leg_count": 2,
    "drawMode": 0,
    "limit_set_count": 2,
    "limit_set_leg_count": 2,
    "startScore": 501,
    "limit_rounds": 1,
    "rounds": 15,
    "point": 1,
    "point_w": 1,
    "point_d": 0,
    "point_l": 0,
    "changeFirst": 0,
    "exitResult": 0,
    "schedule": [],
    "include_leg": 0,
    "autoNext": 1,
    "setOrder": 0,
    "exclude_from_stats": 0,
    "game_setting": [],
  },
  "t_setting": {
    "tournament": 1,
    "t_player_count": 32,
    "t3": 0,
    "auto_continue": 1,
    "disp_no": 1,
    "sequential": 0,
    "show_no_all": 0,
    "limit": 1,
    "limit_leg_count": 3,
    "limit_set_count": 2,
    "limit_set_leg_count": 2,
    "game_setting": [
      {
        "round": -2,
        "limit": 1,
        "limit_leg_count": 4,
        "limit_set_count": 2,
        "limit_set_leg_count": 2,
      },
      {
        "round": -1,
        "limit": 1,
        "limit_leg_count": 5,
        "limit_set_count": 2,
        "limit_set_leg_count": 2,
      },
    ],
    "startScore": 501,
    "limit_rounds": 1,
    "rounds": 15,
    "show_badge": 1,
    "changeFirst": 0,
    "exitResult": 1,
    "schedule": [],
    "autoNext": 1,
    "setOrder": 0,
    "exclude_from_stats": 0,
  },
  "s2_setting": {
    "tournament": 0,
    "t_player_count": 2,
    "t3": 0,
    "auto_continue": 1,
    "exclude_from_stats": 0,
    "limit": 1,
    "limit_leg_count": 2,
    "limit_set_count": 2,
    "limit_set_leg_count": 2,
    "game_setting": [],
    "startScore": 501,
    "limit_rounds": 0,
    "rounds": 15,
    "changeFirst": 0,
    "exitResult": 1,
    "schedule": [],
    "autoNext": 1,
    "setOrder": 0,
  },
  "rr_table": [
    ["P6sQ", "NCho", "u6ET", "ZB4m", "NM2u", "E9Dw"],
    ["rn62", "jJUo", "RV4r", "QlVP", "V2pZ", "XFix"],
    ["Ng8Z", "0cNh", "Vvpc", "Rlrn", "4e4h", "kMZb"],
    ["1LTH", "omW7", "ZqMV", "cJvE", "5B4L", "TvWt"],
    ["uA9n", "3KNU", "rvVp", "nJ5u", "T0uW", ""],
    ["hll5", "jzW1", "2lvg", "9uZV", "S2U5", ""],
    ["uS7X", "MEwa", "P0Qa", "pCBi", "2l5W", ""],
    ["cnfa", "Lgrb", "mBRB", "FNBC", "3kRm", ""],
  ],
  "rr_result": [
    {
      "NCho": {
        "P6sQ": {
          "r": 2,
          "a": 47.13,
        },
        "ZB4m": {
          "r": 0,
          "a": 44.91,
        },
        "E9Dw": {
          "r": 2,
          "a": 56.32,
        },
        "u6ET": {
          "r": 2,
          "a": 50.1,
        },
        "NM2u": {
          "r": 2,
          "a": 37.11,
        },
      },
      "P6sQ": {
        "NCho": {
          "r": 1,
          "a": 50.48,
        },
        "u6ET": {
          "r": 2,
          "a": 51.59,
        },
        "ZB4m": {
          "r": 2,
          "a": 50.95,
        },
        "NM2u": {
          "r": 2,
          "a": 46.97,
        },
        "E9Dw": {
          "r": 1,
          "a": 44.75,
        },
      },
      "E9Dw": {
        "u6ET": {
          "r": 2,
          "a": 65.35,
        },
        "NM2u": {
          "r": 0,
          "a": 45.24,
        },
        "NCho": {
          "r": 1,
          "a": 53.73,
        },
        "ZB4m": {
          "r": 2,
          "a": 61.35,
        },
        "P6sQ": {
          "r": 2,
          "a": 53.52,
        },
      },
      "u6ET": {
        "E9Dw": {
          "r": 0,
          "a": 44.8,
        },
        "P6sQ": {
          "r": 1,
          "a": 42.69,
        },
        "NM2u": {
          "r": 0,
          "a": 37.12,
        },
        "NCho": {
          "r": 0,
          "a": 50.26,
        },
        "ZB4m": {
          "r": 1,
          "a": 36.71,
        },
      },
      "NM2u": {
        "ZB4m": {
          "r": 1,
          "a": 48.58,
        },
        "E9Dw": {
          "r": 2,
          "a": 47.71,
        },
        "u6ET": {
          "r": 2,
          "a": 40.14,
        },
        "P6sQ": {
          "r": 0,
          "a": 36.62,
        },
        "NCho": {
          "r": 0,
          "a": 34.11,
        },
      },
      "ZB4m": {
        "NM2u": {
          "r": 2,
          "a": 51.55,
        },
        "NCho": {
          "r": 2,
          "a": 44.87,
        },
        "P6sQ": {
          "r": 0,
          "a": 38,
        },
        "E9Dw": {
          "r": 0,
          "a": 52.31,
        },
        "u6ET": {
          "r": 2,
          "a": 39.16,
        },
      },
    },
    {
      "jJUo": {
        "rn62": {
          "r": 0,
          "a": 41.54,
        },
        "QlVP": {
          "r": 0,
          "a": 50.06,
        },
        "XFix": {
          "r": 2,
          "a": 40.55,
        },
        "RV4r": {
          "r": 2,
          "a": 39.65,
        },
        "V2pZ": {
          "r": 0,
          "a": 50,
        },
      },
      "rn62": {
        "jJUo": {
          "r": 2,
          "a": 41.18,
        },
        "RV4r": {
          "r": 2,
          "a": 37.22,
        },
        "QlVP": {
          "r": 1,
          "a": 58.06,
        },
        "V2pZ": {
          "r": 0,
          "a": 45.67,
        },
        "XFix": {
          "r": 1,
          "a": 43.04,
        },
      },
      "RV4r": {
        "XFix": {
          "r": 1,
          "a": 40.3,
        },
        "rn62": {
          "r": 1,
          "a": 37.38,
        },
        "V2pZ": {
          "r": 0,
          "a": 55.31,
        },
        "jJUo": {
          "r": 0,
          "a": 38.52,
        },
        "QlVP": {
          "r": 2,
          "a": 46.79,
        },
      },
      "XFix": {
        "RV4r": {
          "r": 2,
          "a": 40.44,
        },
        "V2pZ": {
          "r": 0,
          "a": 43.8,
        },
        "jJUo": {
          "r": 1,
          "a": 39.35,
        },
        "QlVP": {
          "r": 2,
          "a": 41.75,
        },
        "rn62": {
          "r": 2,
          "a": 51.39,
        },
      },
      "QlVP": {
        "V2pZ": {
          "r": 2,
          "a": 62.04,
        },
        "jJUo": {
          "r": 2,
          "a": 56.72,
        },
        "rn62": {
          "r": 2,
          "a": 63,
        },
        "XFix": {
          "r": 0,
          "a": 43.22,
        },
        "RV4r": {
          "r": 1,
          "a": 54.26,
        },
      },
      "V2pZ": {
        "QlVP": {
          "r": 1,
          "a": 55.38,
        },
        "XFix": {
          "r": 2,
          "a": 65.35,
        },
        "RV4r": {
          "r": 2,
          "a": 60.12,
        },
        "rn62": {
          "r": 2,
          "a": 55.67,
        },
        "jJUo": {
          "r": 2,
          "a": 51.83,
        },
      },
    },
    {
      "0cNh": {
        "Ng8Z": {
          "r": 0,
          "a": 36.8,
        },
        "Rlrn": {
          "r": 0,
          "a": 43.43,
        },
        "kMZb": {
          "r": 0,
          "a": 44.55,
        },
        "Vvpc": {
          "r": 0,
          "a": 49.44,
        },
        "4e4h": {
          "r": 1,
          "a": 49.78,
        },
      },
      "Ng8Z": {
        "0cNh": {
          "r": 2,
          "a": 66.8,
        },
        "Vvpc": {
          "r": 2,
          "a": 81.24,
        },
        "Rlrn": {
          "r": 2,
          "a": 81.24,
        },
        "4e4h": {
          "r": 2,
          "a": 58.22,
        },
        "kMZb": {
          "r": 2,
          "a": 76.02,
        },
      },
      "Vvpc": {
        "kMZb": {
          "r": 0,
          "a": 38.83,
        },
        "Ng8Z": {
          "r": 0,
          "a": 60.25,
        },
        "4e4h": {
          "r": 0,
          "a": 53.78,
        },
        "0cNh": {
          "r": 2,
          "a": 53.68,
        },
        "Rlrn": {
          "r": 2,
          "a": 65.35,
        },
      },
      "kMZb": {
        "Vvpc": {
          "r": 2,
          "a": 41.18,
        },
        "4e4h": {
          "r": 2,
          "a": 49.28,
        },
        "0cNh": {
          "r": 2,
          "a": 44.87,
        },
        "Rlrn": {
          "r": 2,
          "a": 51.83,
        },
        "Ng8Z": {
          "r": 1,
          "a": 68.69,
        },
      },
      "4e4h": {
        "Rlrn": {
          "r": 2,
          "a": 48.23,
        },
        "kMZb": {
          "r": 0,
          "a": 46.55,
        },
        "Vvpc": {
          "r": 2,
          "a": 52.74,
        },
        "Ng8Z": {
          "r": 1,
          "a": 53.29,
        },
        "0cNh": {
          "r": 2,
          "a": 55.95,
        },
      },
      "Rlrn": {
        "4e4h": {
          "r": 1,
          "a": 47.09,
        },
        "0cNh": {
          "r": 2,
          "a": 47.71,
        },
        "Ng8Z": {
          "r": 0,
          "a": 60.83,
        },
        "kMZb": {
          "r": 0,
          "a": 50,
        },
        "Vvpc": {
          "r": 0,
          "a": 64.4,
        },
      },
    },
    {
      "1LTH": {
        "omW7": {
          "r": 0,
          "a": 34.55,
        },
        "ZqMV": {
          "r": 0,
          "a": 37.05,
        },
        "cJvE": {
          "r": 1,
          "a": 44.1,
        },
        "5B4L": {
          "r": 0,
          "a": 56.5,
        },
        "TvWt": {
          "r": 2,
          "a": 41.04,
        },
      },
      "omW7": {
        "1LTH": {
          "r": 2,
          "a": 83.5,
        },
        "cJvE": {
          "r": 2,
          "a": 61.35,
        },
        "TvWt": {
          "r": 2,
          "a": 50.1,
        },
        "ZqMV": {
          "r": 2,
          "a": 63.38,
        },
        "5B4L": {
          "r": 0,
          "a": 64.4,
        },
      },
      "TvWt": {
        "ZqMV": {
          "r": 0,
          "a": 42.64,
        },
        "5B4L": {
          "r": 0,
          "a": 35.13,
        },
        "omW7": {
          "r": 0,
          "a": 42.25,
        },
        "cJvE": {
          "r": 1,
          "a": 34.52,
        },
        "1LTH": {
          "r": 1,
          "a": 39.68,
        },
      },
      "ZqMV": {
        "TvWt": {
          "r": 2,
          "a": 44.87,
        },
        "1LTH": {
          "r": 2,
          "a": 51.83,
        },
        "5B4L": {
          "r": 1,
          "a": 59.63,
        },
        "omW7": {
          "r": 1,
          "a": 61.48,
        },
        "cJvE": {
          "r": 2,
          "a": 55.67,
        },
      },
      "5B4L": {
        "cJvE": {
          "r": 2,
          "a": 77.37,
        },
        "TvWt": {
          "r": 2,
          "a": 62.63,
        },
        "ZqMV": {
          "r": 2,
          "a": 62.46,
        },
        "1LTH": {
          "r": 2,
          "a": 61.35,
        },
        "omW7": {
          "r": 2,
          "a": 63.96,
        },
      },
      "cJvE": {
        "5B4L": {
          "r": 1,
          "a": 60.06,
        },
        "omW7": {
          "r": 0,
          "a": 54.19,
        },
        "1LTH": {
          "r": 2,
          "a": 42.71,
        },
        "TvWt": {
          "r": 2,
          "a": 35.63,
        },
        "ZqMV": {
          "r": 0,
          "a": 52.89,
        },
      },
    },
    {
      "3KNU": {
        "uA9n": {
          "r": 1,
          "a": 43.28,
        },
        "nJ5u": {
          "r": 0,
          "a": 44.67,
        },
        "rvVp": {
          "r": 2,
          "a": 42.43,
        },
        "T0uW": {
          "r": 0,
          "a": 45.93,
        },
      },
      "uA9n": {
        "3KNU": {
          "r": 2,
          "a": 51.48,
        },
        "rvVp": {
          "r": 2,
          "a": 50.49,
        },
        "nJ5u": {
          "r": 0,
          "a": 68,
        },
        "T0uW": {
          "r": 0,
          "a": 66.25,
        },
      },
      "T0uW": {
        "nJ5u": {
          "r": 2,
          "a": 77.08,
        },
        "rvVp": {
          "r": 1,
          "a": 65.16,
        },
        "uA9n": {
          "r": 2,
          "a": 83.5,
        },
        "3KNU": {
          "r": 2,
          "a": 62.63,
        },
      },
      "nJ5u": {
        "T0uW": {
          "r": 0,
          "a": 68.77,
        },
        "3KNU": {
          "r": 2,
          "a": 63.96,
        },
        "uA9n": {
          "r": 2,
          "a": 73.32,
        },
        "rvVp": {
          "r": 1,
          "a": 57,
        },
      },
      "rvVp": {
        "uA9n": {
          "r": 1,
          "a": 44.41,
        },
        "T0uW": {
          "r": 2,
          "a": 65.77,
        },
        "3KNU": {
          "r": 1,
          "a": 44.38,
        },
        "nJ5u": {
          "r": 2,
          "a": 54.92,
        },
      },
    },
    {
      "hll5": {
        "jzW1": {
          "r": 0,
          "a": 58.57,
        },
        "2lvg": {
          "r": 2,
          "a": 47.84,
        },
        "9uZV": {
          "r": 0,
          "a": 58.47,
        },
        "S2U5": {
          "r": 2,
          "a": 50.28,
        },
      },
      "jzW1": {
        "hll5": {
          "r": 2,
          "a": 69.91,
        },
        "9uZV": {
          "r": 1,
          "a": 55.1,
        },
        "2lvg": {
          "r": 2,
          "a": 51.76,
        },
        "S2U5": {
          "r": 1,
          "a": 46.71,
        },
      },
      "9uZV": {
        "S2U5": {
          "r": 2,
          "a": 48.24,
        },
        "jzW1": {
          "r": 2,
          "a": 56.7,
        },
        "hll5": {
          "r": 2,
          "a": 65.35,
        },
        "2lvg": {
          "r": 1,
          "a": 42.35,
        },
      },
      "S2U5": {
        "9uZV": {
          "r": 1,
          "a": 52.73,
        },
        "2lvg": {
          "r": 0,
          "a": 35.32,
        },
        "hll5": {
          "r": 1,
          "a": 48.45,
        },
        "jzW1": {
          "r": 2,
          "a": 50.15,
        },
      },
      "2lvg": {
        "hll5": {
          "r": 1,
          "a": 37.69,
        },
        "S2U5": {
          "r": 2,
          "a": 36.07,
        },
        "jzW1": {
          "r": 1,
          "a": 39.38,
        },
        "9uZV": {
          "r": 2,
          "a": 38.24,
        },
      },
    },
    {
      "MEwa": {
        "uS7X": {
          "r": 1,
          "a": 45.58,
        },
        "pCBi": {
          "r": 2,
          "a": 43.93,
        },
        "P0Qa": {
          "r": 2,
          "a": 44.87,
        },
        "2l5W": {
          "r": 0,
          "a": 57.58,
        },
      },
      "uS7X": {
        "MEwa": {
          "r": 2,
          "a": 45.03,
        },
        "P0Qa": {
          "r": 2,
          "a": 36.51,
        },
        "pCBi": {
          "r": 0,
          "a": 43.64,
        },
        "2l5W": {
          "r": 0,
          "a": 40.08,
        },
      },
      "2l5W": {
        "pCBi": {
          "r": 2,
          "a": 85.89,
        },
        "P0Qa": {
          "r": 2,
          "a": 65.35,
        },
        "uS7X": {
          "r": 2,
          "a": 73.32,
        },
        "MEwa": {
          "r": 2,
          "a": 81.24,
        },
      },
      "pCBi": {
        "2l5W": {
          "r": 0,
          "a": 48.83,
        },
        "MEwa": {
          "r": 1,
          "a": 44.48,
        },
        "uS7X": {
          "r": 2,
          "a": 45.55,
        },
        "P0Qa": {
          "r": 2,
          "a": 56.72,
        },
      },
      "P0Qa": {
        "uS7X": {
          "r": 0,
          "a": 34.79,
        },
        "2l5W": {
          "r": 0,
          "a": 46.93,
        },
        "MEwa": {
          "r": 0,
          "a": 43.09,
        },
        "pCBi": {
          "r": 0,
          "a": 37.82,
        },
      },
    },
    {
      "Lgrb": {
        "cnfa": {
          "r": 2,
          "a": 47.15,
        },
        "FNBC": {
          "r": 1,
          "a": 43.04,
        },
        "mBRB": {
          "r": 2,
          "a": 44.87,
        },
        "3kRm": {
          "r": 1,
          "a": 61.78,
        },
      },
      "cnfa": {
        "Lgrb": {
          "r": 1,
          "a": 42.22,
        },
        "mBRB": {
          "r": 2,
          "a": 40.24,
        },
        "FNBC": {
          "r": 0,
          "a": 42.86,
        },
        "3kRm": {
          "r": 1,
          "a": 46.09,
        },
      },
      "3kRm": {
        "FNBC": {
          "r": 2,
          "a": 43.74,
        },
        "mBRB": {
          "r": 0,
          "a": 43.04,
        },
        "cnfa": {
          "r": 2,
          "a": 52.76,
        },
        "Lgrb": {
          "r": 2,
          "a": 60.13,
        },
      },
      "FNBC": {
        "3kRm": {
          "r": 1,
          "a": 44.38,
        },
        "Lgrb": {
          "r": 2,
          "a": 47.07,
        },
        "cnfa": {
          "r": 2,
          "a": 46.97,
        },
        "mBRB": {
          "r": 1,
          "a": 51.92,
        },
      },
      "mBRB": {
        "cnfa": {
          "r": 1,
          "a": 40.14,
        },
        "3kRm": {
          "r": 2,
          "a": 42.94,
        },
        "Lgrb": {
          "r": 0,
          "a": 42.64,
        },
        "FNBC": {
          "r": 2,
          "a": 53.18,
        },
      },
    },
  ],
  "rr_rank": [],
  "t_table": [
    [
      "NCho",
      "hll5",
      "pCBi",
      "ZqMV",
      "FNBC",
      "4e4h",
      "V2pZ",
      "uA9n",
      "Ng8Z",
      "mBRB",
      "nJ5u",
      "E9Dw",
      "jzW1",
      "QlVP",
      "5B4L",
      "uS7X",
      "T0uW",
      "ZB4m",
      "kMZb",
      "Lgrb",
      "omW7",
      "MEwa",
      "9uZV",
      "rn62",
      "2l5W",
      "Vvpc",
      "P6sQ",
      "2lvg",
      "XFix",
      "rvVp",
      "3kRm",
      "cJvE",
    ],
    [
      "NCho",
      "ZqMV",
      "FNBC",
      "uA9n",
      "Ng8Z",
      "E9Dw",
      "jzW1",
      "5B4L",
      "T0uW",
      "Lgrb",
      "omW7",
      "rn62",
      "2l5W",
      "P6sQ",
      "rvVp",
      "cJvE",
    ],
    ["ZqMV", "FNBC", "Ng8Z", "jzW1", "T0uW", "omW7", "2l5W", "rvVp"],
    ["ZqMV", "Ng8Z", "T0uW", "2l5W"],
    ["Ng8Z", "T0uW"],
    ["T0uW"],
  ],
  "t_result": [
    {
      "4e4h": {
        "FNBC": {
          "r": 0,
          "a": 47.32,
        },
      },
      "FNBC": {
        "4e4h": {
          "r": 3,
          "a": 51.83,
        },
      },
      "E9Dw": {
        "nJ5u": {
          "r": 3,
          "a": 58.56,
        },
      },
      "nJ5u": {
        "E9Dw": {
          "r": 1,
          "a": 61.47,
        },
      },
      "QlVP": {
        "jzW1": {
          "r": 1,
          "a": 60.49,
        },
      },
      "jzW1": {
        "QlVP": {
          "r": 3,
          "a": 64.24,
        },
      },
      "Ng8Z": {
        "mBRB": {
          "r": 3,
          "a": 54.33,
        },
      },
      "mBRB": {
        "Ng8Z": {
          "r": 0,
          "a": 45.33,
        },
      },
      "ZqMV": {
        "pCBi": {
          "r": 3,
          "a": 58.56,
        },
      },
      "pCBi": {
        "ZqMV": {
          "r": 0,
          "a": 46.36,
        },
      },
      "NCho": {
        "hll5": {
          "r": 3,
          "a": 55.36,
        },
      },
      "hll5": {
        "NCho": {
          "r": 2,
          "a": 52.72,
        },
      },
      "V2pZ": {
        "uA9n": {
          "r": 2,
          "a": 52.82,
        },
      },
      "uA9n": {
        "V2pZ": {
          "r": 3,
          "a": 53.03,
        },
      },
      "5B4L": {
        "uS7X": {
          "r": 3,
          "a": 57.81,
        },
      },
      "uS7X": {
        "5B4L": {
          "r": 0,
          "a": 32,
        },
      },
      "T0uW": {
        "ZB4m": {
          "r": 3,
          "a": 67.3,
        },
      },
      "ZB4m": {
        "T0uW": {
          "r": 0,
          "a": 53.48,
        },
      },
      "Lgrb": {
        "kMZb": {
          "r": 3,
          "a": 47.05,
        },
      },
      "kMZb": {
        "Lgrb": {
          "r": 2,
          "a": 47.44,
        },
      },
      "MEwa": {
        "omW7": {
          "r": 0,
          "a": 42.39,
        },
      },
      "omW7": {
        "MEwa": {
          "r": 3,
          "a": 65.35,
        },
      },
      "9uZV": {
        "rn62": {
          "r": 1,
          "a": 48.4,
        },
      },
      "rn62": {
        "9uZV": {
          "r": 3,
          "a": 46.24,
        },
      },
      "2l5W": {
        "Vvpc": {
          "r": 3,
          "a": 72.73,
        },
      },
      "Vvpc": {
        "2l5W": {
          "r": 0,
          "a": 61.89,
        },
      },
      "2lvg": {
        "P6sQ": {
          "r": 0,
          "a": 40.4,
        },
      },
      "P6sQ": {
        "2lvg": {
          "r": 3,
          "a": 51.24,
        },
      },
      "XFix": {
        "rvVp": {
          "r": 1,
          "a": 41.4,
        },
      },
      "rvVp": {
        "XFix": {
          "r": 3,
          "a": 42.86,
        },
      },
      "3kRm": {
        "cJvE": {
          "r": 0,
          "a": 44.85,
        },
      },
      "cJvE": {
        "3kRm": {
          "r": 3,
          "a": 54.33,
        },
      },
    },
    {
      "E9Dw": {
        "Ng8Z": {
          "r": 1,
          "a": 58.57,
        },
      },
      "Ng8Z": {
        "E9Dw": {
          "r": 3,
          "a": 67.76,
        },
      },
      "FNBC": {
        "uA9n": {
          "r": 3,
          "a": 55.22,
        },
      },
      "uA9n": {
        "FNBC": {
          "r": 1,
          "a": 50.23,
        },
      },
      "NCho": {
        "ZqMV": {
          "r": 0,
          "a": 55.43,
        },
      },
      "ZqMV": {
        "NCho": {
          "r": 3,
          "a": 70.45,
        },
      },
      "5B4L": {
        "jzW1": {
          "r": 2,
          "a": 62.13,
        },
      },
      "jzW1": {
        "5B4L": {
          "r": 3,
          "a": 57,
        },
      },
      "omW7": {
        "rn62": {
          "r": 3,
          "a": 59.03,
        },
      },
      "rn62": {
        "omW7": {
          "r": 2,
          "a": 58.66,
        },
      },
      "2l5W": {
        "P6sQ": {
          "r": 3,
          "a": 71.57,
        },
      },
      "P6sQ": {
        "2l5W": {
          "r": 0,
          "a": 56.9,
        },
      },
      "cJvE": {
        "rvVp": {
          "r": 0,
          "a": 45.78,
        },
      },
      "rvVp": {
        "cJvE": {
          "r": 3,
          "a": 46.48,
        },
      },
      "Lgrb": {
        "T0uW": {
          "r": 0,
          "a": 43.5,
        },
      },
      "T0uW": {
        "Lgrb": {
          "r": 3,
          "a": 57.81,
        },
      },
    },
    {
      "2l5W": {
        "rvVp": {
          "r": 3,
          "a": 80.52,
        },
      },
      "rvVp": {
        "2l5W": {
          "r": 0,
          "a": 50.33,
        },
      },
      "FNBC": {
        "ZqMV": {
          "r": 0,
          "a": 53.17,
        },
      },
      "ZqMV": {
        "FNBC": {
          "r": 3,
          "a": 61.77,
        },
      },
      "T0uW": {
        "omW7": {
          "r": 3,
          "a": 69.68,
        },
      },
      "omW7": {
        "T0uW": {
          "r": 1,
          "a": 76.03,
        },
      },
      "Ng8Z": {
        "jzW1": {
          "r": 3,
          "a": 70.99,
        },
      },
      "jzW1": {
        "Ng8Z": {
          "r": 1,
          "a": 55.48,
        },
      },
    },
    {
      "Ng8Z": {
        "ZqMV": {
          "r": 4,
          "a": 62.21,
        },
      },
      "ZqMV": {
        "Ng8Z": {
          "r": 3,
          "a": 64.64,
        },
      },
      "2l5W": {
        "T0uW": {
          "r": 0,
          "a": 73.08,
        },
      },
      "T0uW": {
        "2l5W": {
          "r": 4,
          "a": 76.1,
        },
      },
    },
    {
      "Ng8Z": {
        "T0uW": {
          "r": 3,
          "a": 65.96,
        },
      },
      "T0uW": {
        "Ng8Z": {
          "r": 5,
          "a": 71.75,
        },
      },
    },
  ],
  "s2_table": [],
  "s2_result": [],
  "t_title": ["", ""],
  "t_init": {
    "0_0": "1-1",
    "0_1": "6-4",
    "0_2": "7-2",
    "0_3": "4-3",
    "0_4": "8-2",
    "0_5": "3-3",
    "0_6": "2-1",
    "0_7": "5-4",
    "0_8": "3-1",
    "0_9": "8-4",
    "0_10": "5-2",
    "0_11": "1-3",
    "0_12": "6-2",
    "0_13": "2-3",
    "0_14": "4-1",
    "0_15": "7-4",
    "0_16": "5-1",
    "0_17": "1-4",
    "0_18": "3-2",
    "0_19": "8-3",
    "0_20": "4-2",
    "0_21": "7-3",
    "0_22": "6-1",
    "0_23": "2-4",
    "0_24": "7-1",
    "0_25": "3-4",
    "0_26": "1-2",
    "0_27": "6-3",
    "0_28": "2-2",
    "0_29": "5-3",
    "0_30": "8-1",
    "0_31": "4-4",
  },
  "t3_table": [],
  "s2_3_table": [],
  "t3_result": [],
  "s2_3_result": [],
  "m_table": [],
  "m_result": [],
  "m_setting": {
    "matchs": 0,
    "match_count": 1,
    "auto_continue": 1,
    "direction": 1,
    "limit": 1,
    "limit_leg_count": 2,
    "limit_set_count": 2,
    "limit_set_leg_count": 2,
    "startScore": 501,
    "limit_rounds": 0,
    "rounds": 15,
    "changeFirst": 0,
    "exitResult": 0,
    "schedule": [],
    "autoNext": 1,
    "setOrder": 0,
    "exclude_from_stats": 0,
  },
  "lg_table": [],
  "lg_result": [],
  "lg_rank": [],
  "team_games": 0,
  "name_sep": "",
  "dynamic_avg": 0,
  "private": 0,
  "entry_list": [
    {
      "tpid": "Vvpc",
      "name": "(MPB#88) Klopan Miroslav",
    },
    {
      "tpid": "2l5W",
      "name": "(MPB#9) Fe\u010dko Tom\u00e1\u0161",
    },
    {
      "tpid": "kMZb",
      "name": "(MPB#90) Szepesi Ladislav",
    },
    {
      "tpid": "uA9n",
      "name": "(MPB#4) Kubinec Martin",
    },
    {
      "tpid": "rvVp",
      "name": "(MPB#116) Klopan Rudolf",
    },
    {
      "tpid": "XFix",
      "name": "(MPB#265) Farkas Kamil",
    },
    {
      "tpid": "jzW1",
      "name": "(MPB#161) Mihalik Roman",
    },
    {
      "tpid": "1LTH",
      "name": "(MPB#66) Tarek Jana",
    },
    {
      "tpid": "T0uW",
      "name": "(MPB#93) Gosar Jurij",
    },
    {
      "tpid": "P6sQ",
      "name": "(MPB#27) Buffa Jozef",
    },
    {
      "tpid": "nJ5u",
      "name": "(MPB#147) \u0164ap\u00e1k Peter",
    },
    {
      "tpid": "3KNU",
      "name": "(MPB#47) Mikl\u00f3s Adri\u00e1n",
    },
    {
      "tpid": "QlVP",
      "name": "(MPB#73) Sch\u00f6n Richard",
    },
    {
      "tpid": "5B4L",
      "name": "(MPB#63) Mi\u0161\u010d\u00edk Peter",
    },
    {
      "tpid": "E9Dw",
      "name": "(MPB#85) Farka\u0161 Peter",
    },
    {
      "tpid": "Lgrb",
      "name": "(MPB#40) \u0160uka\u013e Peter",
    },
    {
      "tpid": "MEwa",
      "name": "(MPB#134) Fuksa Alexander",
    },
    {
      "tpid": "Rlrn",
      "name": "(MPB#271) \u010cul\u00e1k Ivan",
    },
    {
      "tpid": "jJUo",
      "name": "(MPB#91) Pavli\u0161 Jozef",
    },
    {
      "tpid": "cnfa",
      "name": "(MPB#59) Samard\u017eia Peter",
    },
    {
      "tpid": "4e4h",
      "name": "(MPB#26) Entner Miro",
    },
    {
      "tpid": "mBRB",
      "name": "(MPB#255) Chvostek Drahoslav",
    },
    {
      "tpid": "pCBi",
      "name": "(MPB#10) Brindz\u00edk Miroslav",
    },
    {
      "tpid": "ZB4m",
      "name": "(MPB#280) Lu\u010dko Martin",
    },
    {
      "tpid": "rn62",
      "name": "(MPB#54) Kuba Franti\u0161ek",
    },
    {
      "tpid": "3kRm",
      "name": "(MPB#133) Mikul\u00e1\u0161 Vladim\u00edr",
    },
    {
      "tpid": "NM2u",
      "name": "(MPB#221) Bord\u00e1\u010d Juraj",
    },
    {
      "tpid": "ZqMV",
      "name": "(MPB#111) Kotris Pavol",
    },
    {
      "tpid": "S2U5",
      "name": "(MPB#238) \u017dilinsk\u00fd Patrik",
    },
    {
      "tpid": "V2pZ",
      "name": "(MPB#11) Dominik Mihaly",
    },
    {
      "tpid": "NCho",
      "name": "(MPB#224) Durfina Robert",
    },
    {
      "tpid": "RV4r",
      "name": "(MPB#125) Glezo Juraj",
    },
    {
      "tpid": "omW7",
      "name": "(MPB#130) Pivar\u010d \u013dubo\u0161",
    },
    {
      "tpid": "Ng8Z",
      "name": "(MPB#7) Such\u00e1nek \u013duboslav",
    },
    {
      "tpid": "u6ET",
      "name": "(MPB#256) Prizbul Marek",
    },
    {
      "tpid": "uS7X",
      "name": "(MPB#291) Balej Jozef",
    },
    {
      "tpid": "0cNh",
      "name": "(MPB#243) \u0160ufliarska Denisa",
    },
    {
      "tpid": "2lvg",
      "name": "(MPB#99) Habala Vladimir",
    },
    {
      "tpid": "FNBC",
      "name": "(MPB#141) Rupp Jaroslav",
    },
    {
      "tpid": "cJvE",
      "name": "(MPB#150) Felix \u013dudov\u00edt",
    },
    {
      "tpid": "9uZV",
      "name": "(MPB#159) Bug\u00e1r Tomas",
    },
    {
      "tpid": "hll5",
      "name": "(MPB#218) Kone\u010dn\u00fd Miroslav",
    },
    {
      "tpid": "P0Qa",
      "name": "(MPB#78) Kr\u010dov\u00e1 Nikola",
    },
    {
      "tpid": "TvWt",
      "name": "Tk\u00e1\u010d Anton",
    },
  ],
  "stats": {
    "NCho": {
      "score": 9434,
      "darts": 567,
      "winLeg": 11,
      "leg": 20,
      "a_b": 10,
      "w_b": 6,
      "winSet": 5,
      "set": 7,
      "ton00": 19,
      "ton40": 2,
      "ton80": 0,
      "highOut": 56,
      "best": 22,
      "worst": 43,
      "winDarts": 336,
      "winCnt": 11,
      "f9Score": 3465,
      "f9Darts": 180,
      "r_g": 1,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "P6sQ": {
      "score": 8858,
      "darts": 529,
      "winLeg": 11,
      "leg": 19,
      "a_b": 9,
      "w_b": 4,
      "winSet": 4,
      "set": 7,
      "ton00": 9,
      "ton40": 1,
      "ton80": 0,
      "highOut": 78,
      "best": 22,
      "worst": 37,
      "winDarts": 313,
      "winCnt": 11,
      "f9Score": 3100,
      "f9Darts": 171,
      "r_g": 1,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "E9Dw": {
      "score": 9346,
      "darts": 499,
      "winLeg": 11,
      "leg": 20,
      "a_b": 10,
      "w_b": 5,
      "winSet": 4,
      "set": 7,
      "ton00": 8,
      "ton40": 2,
      "ton80": 0,
      "highOut": 60,
      "best": 20,
      "worst": 30,
      "winDarts": 280,
      "winCnt": 11,
      "f9Score": 3617,
      "f9Darts": 180,
      "r_g": 1,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "u6ET": {
      "score": 5188,
      "darts": 378,
      "winLeg": 2,
      "leg": 12,
      "a_b": 7,
      "w_b": 1,
      "winSet": 0,
      "set": 5,
      "ton00": 4,
      "ton40": 0,
      "ton80": 0,
      "highOut": 16,
      "best": 39,
      "worst": 46,
      "winDarts": 85,
      "winCnt": 2,
      "f9Score": 1398,
      "f9Darts": 108,
      "r_g": 1,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "NM2u": {
      "score": 5107,
      "darts": 369,
      "winLeg": 5,
      "leg": 11,
      "a_b": 5,
      "w_b": 2,
      "winSet": 2,
      "set": 5,
      "ton00": 5,
      "ton40": 2,
      "ton80": 0,
      "highOut": 51,
      "best": 26,
      "worst": 46,
      "winDarts": 166,
      "winCnt": 5,
      "f9Score": 1606,
      "f9Darts": 99,
      "r_g": 1,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "ZB4m": {
      "score": 6680,
      "darts": 437,
      "winLeg": 6,
      "leg": 15,
      "a_b": 8,
      "w_b": 3,
      "winSet": 3,
      "set": 6,
      "ton00": 10,
      "ton40": 2,
      "ton80": 0,
      "highOut": 60,
      "best": 25,
      "worst": 42,
      "winDarts": 197,
      "winCnt": 6,
      "f9Score": 2423,
      "f9Darts": 135,
      "r_g": 1,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "jJUo": {
      "score": 5263,
      "darts": 364,
      "winLeg": 4,
      "leg": 11,
      "a_b": 6,
      "w_b": 2,
      "winSet": 2,
      "set": 5,
      "ton00": 4,
      "ton40": 0,
      "ton80": 0,
      "highOut": 60,
      "best": 29,
      "worst": 46,
      "winDarts": 149,
      "winCnt": 4,
      "f9Score": 1671,
      "f9Darts": 99,
      "r_g": 2,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "rn62": {
      "score": 9976,
      "darts": 635,
      "winLeg": 11,
      "leg": 22,
      "a_b": 13,
      "w_b": 5,
      "winSet": 3,
      "set": 7,
      "ton00": 6,
      "ton40": 1,
      "ton80": 0,
      "highOut": 78,
      "best": 18,
      "worst": 46,
      "winDarts": 354,
      "winCnt": 11,
      "f9Score": 3295,
      "f9Darts": 198,
      "r_g": 2,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "RV4r": {
      "score": 6144,
      "darts": 438,
      "winLeg": 4,
      "leg": 13,
      "a_b": 5,
      "w_b": 1,
      "winSet": 1,
      "set": 5,
      "ton00": 5,
      "ton40": 0,
      "ton80": 0,
      "highOut": 64,
      "best": 29,
      "worst": 33,
      "winDarts": 126,
      "winCnt": 4,
      "f9Score": 1787,
      "f9Darts": 117,
      "r_g": 2,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "XFix": {
      "score": 7891,
      "darts": 556,
      "winLeg": 8,
      "leg": 17,
      "a_b": 8,
      "w_b": 4,
      "winSet": 3,
      "set": 6,
      "ton00": 9,
      "ton40": 0,
      "ton80": 0,
      "highOut": 42,
      "best": 21,
      "worst": 41,
      "winDarts": 280,
      "winCnt": 8,
      "f9Score": 2755,
      "f9Darts": 153,
      "r_g": 2,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "QlVP": {
      "score": 8051,
      "darts": 426,
      "winLeg": 8,
      "leg": 17,
      "a_b": 9,
      "w_b": 3,
      "winSet": 3,
      "set": 6,
      "ton00": 13,
      "ton40": 1,
      "ton80": 0,
      "highOut": 54,
      "best": 17,
      "worst": 27,
      "winDarts": 192,
      "winCnt": 8,
      "f9Score": 2937,
      "f9Darts": 153,
      "r_g": 2,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "V2pZ": {
      "score": 7786,
      "darts": 419,
      "winLeg": 11,
      "leg": 16,
      "a_b": 8,
      "w_b": 4,
      "winSet": 4,
      "set": 6,
      "ton00": 14,
      "ton40": 2,
      "ton80": 0,
      "highOut": 59,
      "best": 20,
      "worst": 30,
      "winDarts": 290,
      "winCnt": 11,
      "f9Score": 3142,
      "f9Darts": 144,
      "r_g": 2,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "0cNh": {
      "score": 4678,
      "darts": 309,
      "winLeg": 1,
      "leg": 11,
      "a_b": 6,
      "w_b": 1,
      "winSet": 0,
      "set": 5,
      "ton00": 1,
      "ton40": 1,
      "ton80": 0,
      "highOut": 57,
      "best": 24,
      "worst": 24,
      "winDarts": 24,
      "winCnt": 1,
      "f9Score": 1544,
      "f9Darts": 99,
      "r_g": 3,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "Ng8Z": {
      "score": 18127,
      "darts": 821,
      "winLeg": 26,
      "leg": 38,
      "a_b": 18,
      "w_b": 10,
      "winSet": 9,
      "set": 10,
      "ton00": 29,
      "ton40": 9,
      "ton80": 5,
      "highOut": 113,
      "best": 15,
      "worst": 37,
      "winDarts": 575,
      "winCnt": 26,
      "f9Score": 8513,
      "f9Darts": 342,
      "r_g": 3,
      "rank": 2,
      "rnd": -1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "Vvpc": {
      "score": 5803,
      "darts": 321,
      "winLeg": 4,
      "leg": 13,
      "a_b": 7,
      "w_b": 2,
      "winSet": 2,
      "set": 6,
      "ton00": 10,
      "ton40": 1,
      "ton80": 0,
      "highOut": 40,
      "best": 19,
      "worst": 30,
      "winDarts": 102,
      "winCnt": 4,
      "f9Score": 2215,
      "f9Darts": 117,
      "r_g": 3,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "kMZb": {
      "score": 7794,
      "darts": 472,
      "winLeg": 11,
      "leg": 16,
      "a_b": 9,
      "w_b": 7,
      "winSet": 4,
      "set": 6,
      "ton00": 12,
      "ton40": 2,
      "ton80": 1,
      "highOut": 60,
      "best": 17,
      "worst": 37,
      "winDarts": 337,
      "winCnt": 11,
      "f9Score": 2997,
      "f9Darts": 144,
      "r_g": 3,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "4e4h": {
      "score": 7492,
      "darts": 444,
      "winLeg": 7,
      "leg": 16,
      "a_b": 7,
      "w_b": 2,
      "winSet": 3,
      "set": 6,
      "ton00": 7,
      "ton40": 0,
      "ton80": 0,
      "highOut": 76,
      "best": 21,
      "worst": 36,
      "winDarts": 195,
      "winCnt": 7,
      "f9Score": 2574,
      "f9Darts": 144,
      "r_g": 3,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "Rlrn": {
      "score": 5045,
      "darts": 290,
      "winLeg": 3,
      "leg": 11,
      "a_b": 6,
      "w_b": 1,
      "winSet": 1,
      "set": 5,
      "ton00": 8,
      "ton40": 3,
      "ton80": 0,
      "highOut": 32,
      "best": 25,
      "worst": 38,
      "winDarts": 98,
      "winCnt": 3,
      "f9Score": 2145,
      "f9Darts": 99,
      "r_g": 3,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "1LTH": {
      "score": 4949,
      "darts": 347,
      "winLeg": 3,
      "leg": 12,
      "a_b": 6,
      "w_b": 0,
      "winSet": 1,
      "set": 5,
      "ton00": 5,
      "ton40": 1,
      "ton80": 0,
      "highOut": 30,
      "best": 34,
      "worst": 46,
      "winDarts": 117,
      "winCnt": 3,
      "f9Score": 1714,
      "f9Darts": 108,
      "r_g": 4,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "omW7": {
      "score": 11262,
      "darts": 526,
      "winLeg": 15,
      "leg": 23,
      "a_b": 11,
      "w_b": 7,
      "winSet": 6,
      "set": 8,
      "ton00": 25,
      "ton40": 8,
      "ton80": 2,
      "highOut": 102,
      "best": 16,
      "worst": 41,
      "winDarts": 361,
      "winCnt": 15,
      "f9Score": 4835,
      "f9Darts": 207,
      "r_g": 4,
      "rank": 5,
      "rnd": 3,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "TvWt": {
      "score": 5204,
      "darts": 406,
      "winLeg": 2,
      "leg": 12,
      "a_b": 6,
      "w_b": 0,
      "winSet": 0,
      "set": 5,
      "ton00": 3,
      "ton40": 0,
      "ton80": 0,
      "highOut": 22,
      "best": 29,
      "worst": 35,
      "winDarts": 64,
      "winCnt": 2,
      "f9Score": 1442,
      "f9Darts": 108,
      "r_g": 4,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "ZqMV": {
      "score": 13784,
      "darts": 693,
      "winLeg": 20,
      "leg": 28,
      "a_b": 14,
      "w_b": 10,
      "winSet": 6,
      "set": 9,
      "ton00": 29,
      "ton40": 5,
      "ton80": 1,
      "highOut": 112,
      "best": 18,
      "worst": 35,
      "winDarts": 507,
      "winCnt": 20,
      "f9Score": 5749,
      "f9Darts": 252,
      "r_g": 4,
      "rank": 3,
      "rnd": -2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "5B4L": {
      "score": 9963,
      "darts": 471,
      "winLeg": 15,
      "leg": 20,
      "a_b": 10,
      "w_b": 7,
      "winSet": 6,
      "set": 7,
      "ton00": 23,
      "ton40": 3,
      "ton80": 2,
      "highOut": 86,
      "best": 17,
      "worst": 41,
      "winDarts": 354,
      "winCnt": 15,
      "f9Score": 4777,
      "f9Darts": 180,
      "r_g": 4,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "cJvE": {
      "score": 8824,
      "darts": 563,
      "winLeg": 8,
      "leg": 19,
      "a_b": 9,
      "w_b": 2,
      "winSet": 3,
      "set": 7,
      "ton00": 13,
      "ton40": 0,
      "ton80": 0,
      "highOut": 67,
      "best": 21,
      "worst": 46,
      "winDarts": 267,
      "winCnt": 8,
      "f9Score": 3338,
      "f9Darts": 171,
      "r_g": 4,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "3KNU": {
      "score": 4013,
      "darts": 276,
      "winLeg": 3,
      "leg": 10,
      "a_b": 5,
      "w_b": 0,
      "winSet": 1,
      "set": 4,
      "ton00": 2,
      "ton40": 0,
      "ton80": 0,
      "highOut": 44,
      "best": 30,
      "worst": 41,
      "winDarts": 108,
      "winCnt": 3,
      "f9Score": 1654,
      "f9Darts": 90,
      "r_g": 5,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "uA9n": {
      "score": 8953,
      "darts": 498,
      "winLeg": 8,
      "leg": 19,
      "a_b": 8,
      "w_b": 1,
      "winSet": 3,
      "set": 6,
      "ton00": 11,
      "ton40": 1,
      "ton80": 0,
      "highOut": 99,
      "best": 21,
      "worst": 35,
      "winDarts": 219,
      "winCnt": 8,
      "f9Score": 2860,
      "f9Darts": 171,
      "r_g": 5,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "T0uW": {
      "score": 15234,
      "darts": 657,
      "winLeg": 25,
      "leg": 31,
      "a_b": 15,
      "w_b": 12,
      "winSet": 8,
      "set": 9,
      "ton00": 32,
      "ton40": 8,
      "ton80": 5,
      "highOut": 114,
      "best": 15,
      "worst": 32,
      "winDarts": 531,
      "winCnt": 25,
      "f9Score": 7537,
      "f9Darts": 279,
      "r_g": 5,
      "rank": 1,
      "rnd": -1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "nJ5u": {
      "score": 6249,
      "darts": 296,
      "winLeg": 6,
      "leg": 13,
      "a_b": 6,
      "w_b": 3,
      "winSet": 2,
      "set": 5,
      "ton00": 15,
      "ton40": 3,
      "ton80": 0,
      "highOut": 32,
      "best": 19,
      "worst": 30,
      "winDarts": 137,
      "winCnt": 6,
      "f9Score": 2762,
      "f9Darts": 117,
      "r_g": 5,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "rvVp": {
      "score": 9982,
      "darts": 618,
      "winLeg": 12,
      "leg": 22,
      "a_b": 14,
      "w_b": 6,
      "winSet": 4,
      "set": 7,
      "ton00": 18,
      "ton40": 3,
      "ton80": 0,
      "highOut": 72,
      "best": 21,
      "worst": 40,
      "winDarts": 354,
      "winCnt": 12,
      "f9Score": 3678,
      "f9Darts": 198,
      "r_g": 5,
      "rank": 5,
      "rnd": 3,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "hll5": {
      "score": 6942,
      "darts": 398,
      "winLeg": 6,
      "leg": 15,
      "a_b": 9,
      "w_b": 4,
      "winSet": 2,
      "set": 5,
      "ton00": 10,
      "ton40": 1,
      "ton80": 0,
      "highOut": 85,
      "best": 24,
      "worst": 34,
      "winDarts": 167,
      "winCnt": 6,
      "f9Score": 2663,
      "f9Darts": 135,
      "r_g": 6,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "jzW1": {
      "score": 10866,
      "darts": 580,
      "winLeg": 13,
      "leg": 24,
      "a_b": 12,
      "w_b": 4,
      "winSet": 4,
      "set": 7,
      "ton00": 9,
      "ton40": 4,
      "ton80": 0,
      "highOut": 94,
      "best": 21,
      "worst": 35,
      "winDarts": 325,
      "winCnt": 13,
      "f9Score": 4587,
      "f9Darts": 216,
      "r_g": 6,
      "rank": 5,
      "rnd": 3,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "9uZV": {
      "score": 7282,
      "darts": 435,
      "winLeg": 8,
      "leg": 15,
      "a_b": 8,
      "w_b": 3,
      "winSet": 3,
      "set": 5,
      "ton00": 9,
      "ton40": 4,
      "ton80": 0,
      "highOut": 153,
      "best": 18,
      "worst": 36,
      "winDarts": 222,
      "winCnt": 8,
      "f9Score": 2857,
      "f9Darts": 135,
      "r_g": 6,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "S2U5": {
      "score": 5324,
      "darts": 342,
      "winLeg": 4,
      "leg": 11,
      "a_b": 5,
      "w_b": 1,
      "winSet": 1,
      "set": 4,
      "ton00": 7,
      "ton40": 0,
      "ton80": 0,
      "highOut": 40,
      "best": 20,
      "worst": 28,
      "winDarts": 102,
      "winCnt": 4,
      "f9Score": 1952,
      "f9Darts": 99,
      "r_g": 6,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "2lvg": {
      "score": 5884,
      "darts": 460,
      "winLeg": 6,
      "leg": 14,
      "a_b": 5,
      "w_b": 1,
      "winSet": 2,
      "set": 5,
      "ton00": 7,
      "ton40": 0,
      "ton80": 0,
      "highOut": 28,
      "best": 35,
      "worst": 46,
      "winDarts": 242,
      "winCnt": 6,
      "f9Score": 1993,
      "f9Darts": 126,
      "r_g": 6,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "MEwa": {
      "score": 5636,
      "darts": 371,
      "winLeg": 5,
      "leg": 13,
      "a_b": 6,
      "w_b": 2,
      "winSet": 2,
      "set": 5,
      "ton00": 8,
      "ton40": 0,
      "ton80": 0,
      "highOut": 51,
      "best": 29,
      "worst": 36,
      "winDarts": 164,
      "winCnt": 5,
      "f9Score": 1740,
      "f9Darts": 117,
      "r_g": 7,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "uS7X": {
      "score": 4735,
      "darts": 359,
      "winLeg": 4,
      "leg": 12,
      "a_b": 7,
      "w_b": 2,
      "winSet": 2,
      "set": 5,
      "ton00": 2,
      "ton40": 0,
      "ton80": 0,
      "highOut": 65,
      "best": 31,
      "worst": 46,
      "winDarts": 153,
      "winCnt": 4,
      "f9Score": 1407,
      "f9Darts": 108,
      "r_g": 7,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "2l5W": {
      "score": 10344,
      "darts": 415,
      "winLeg": 17,
      "leg": 21,
      "a_b": 9,
      "w_b": 7,
      "winSet": 7,
      "set": 8,
      "ton00": 24,
      "ton40": 10,
      "ton80": 3,
      "highOut": 139,
      "best": 13,
      "worst": 25,
      "winDarts": 340,
      "winCnt": 17,
      "f9Score": 5437,
      "f9Darts": 189,
      "r_g": 7,
      "rank": 3,
      "rnd": -2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "pCBi": {
      "score": 5202,
      "darts": 328,
      "winLeg": 5,
      "leg": 12,
      "a_b": 6,
      "w_b": 3,
      "winSet": 2,
      "set": 5,
      "ton00": 7,
      "ton40": 2,
      "ton80": 0,
      "highOut": 40,
      "best": 21,
      "worst": 37,
      "winDarts": 151,
      "winCnt": 5,
      "f9Score": 1935,
      "f9Darts": 108,
      "r_g": 7,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "P0Qa": {
      "score": 3269,
      "darts": 246,
      "winLeg": 0,
      "leg": 8,
      "a_b": 4,
      "w_b": 0,
      "winSet": 0,
      "set": 4,
      "ton00": 0,
      "ton40": 0,
      "ton80": 0,
      "highOut": 0,
      "best": 0,
      "worst": 0,
      "winDarts": 0,
      "winCnt": 0,
      "f9Score": 1166,
      "f9Darts": 72,
      "r_g": 7,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "Lgrb": {
      "score": 8782,
      "darts": 555,
      "winLeg": 9,
      "leg": 19,
      "a_b": 9,
      "w_b": 5,
      "winSet": 3,
      "set": 6,
      "ton00": 7,
      "ton40": 1,
      "ton80": 0,
      "highOut": 75,
      "best": 23,
      "worst": 42,
      "winDarts": 279,
      "winCnt": 9,
      "f9Score": 3120,
      "f9Darts": 171,
      "r_g": 8,
      "rank": 9,
      "rnd": 2,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "cnfa": {
      "score": 4941,
      "darts": 348,
      "winLeg": 4,
      "leg": 11,
      "a_b": 5,
      "w_b": 1,
      "winSet": 1,
      "set": 4,
      "ton00": 3,
      "ton40": 2,
      "ton80": 0,
      "highOut": 43,
      "best": 23,
      "worst": 46,
      "winDarts": 136,
      "winCnt": 4,
      "f9Score": 1575,
      "f9Darts": 99,
      "r_g": 8,
      "rank": 0,
      "rnd": "",
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "3kRm": {
      "score": 6393,
      "darts": 396,
      "winLeg": 6,
      "leg": 14,
      "a_b": 7,
      "w_b": 3,
      "winSet": 3,
      "set": 5,
      "ton00": 7,
      "ton40": 1,
      "ton80": 0,
      "highOut": 32,
      "best": 22,
      "worst": 35,
      "winDarts": 171,
      "winCnt": 6,
      "f9Score": 2367,
      "f9Darts": 126,
      "r_g": 8,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "FNBC": {
      "score": 10172,
      "darts": 609,
      "winLeg": 12,
      "leg": 21,
      "a_b": 10,
      "w_b": 7,
      "winSet": 4,
      "set": 7,
      "ton00": 11,
      "ton40": 0,
      "ton80": 0,
      "highOut": 52,
      "best": 23,
      "worst": 36,
      "winDarts": 354,
      "winCnt": 12,
      "f9Score": 3704,
      "f9Darts": 189,
      "r_g": 8,
      "rank": 5,
      "rnd": 3,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
    "mBRB": {
      "score": 6138,
      "darts": 412,
      "winLeg": 5,
      "leg": 13,
      "a_b": 8,
      "w_b": 3,
      "winSet": 2,
      "set": 5,
      "ton00": 6,
      "ton40": 0,
      "ton80": 0,
      "highOut": 70,
      "best": 26,
      "worst": 36,
      "winDarts": 157,
      "winCnt": 5,
      "f9Score": 1820,
      "f9Darts": 117,
      "r_g": 8,
      "rank": 17,
      "rnd": 1,
      "rank_s2": 0,
      "rnd_s2": "",
      "a": 0,
      "acnt": 0,
    },
  },
};
