export const data = [
  {
    id: 1,
    name: "Griffith Lane",
    email: false,
    address: "P.O. Box 539, 5951 Nulla Av.",
    country: "Ukraine",
    test: null,
    date: "Oct 20, 2022",
  },
  {
    id: 2,
    name: "Logan Pollard",
    email: "augue.porttitor.interdum@protonmail.net",
    address: "7957 Augue St.",
    country: "Philippines",
  },
  {
    id: 3,
    name: "Hyacinth Levine",
    address: "Ap #443-9166 Vitae Street",
    country: "Austria",
    date: "Oct 1, 2022",
  },
  {
    id: 4,
    name: "Maxine Shields",
    email: "ipsum@icloud.org",
    address: "P.O. Box 687, 4339 Eget Avenue",
    country: "Costa Rica",
    date: "Mar 12, 2023",
  },
  {
    id: 5,
    name: "Germane Fernandez",
    email: "pede.et@yahoo.couk",
    address: "P.O. Box 693, 6291 Tempor Street",
    country: "Pakistan",
    date: "Apr 10, 2023",
  },
  {
    id: 6,
    name: "Griffith Lane",
    email: "rutrum@icloud.couk",
    address: "P.O. Box 539, 5951 Nulla Av.",
    country: "Ukraine",
    date: "Oct 20, 2022",
  },
  {
    id: 7,
    name: "Logan Pollard",
    email: "augue.porttitor.interdum@protonmail.net",
    address: "7957 Augue St.",
    country: "Philippines",
    date: "Jun 7, 2022",
  },
  {
    id: 8,
    name: "Hyacinth Levine",
    email: "ultricies@protonmail.edu",
    address: "Ap #443-9166 Vitae Street",
    country: "Austria",
    date: "Oct 1, 2022",
  },
  {
    id: 9,
    name: "Maxine Shields",
    email: "ipsum@icloud.org",
    address: "P.O. Box 687, 4339 Eget Avenue",
    country: "Costa Rica",
    date: "Mar 12, 2023",
  },
  {
    id: 10,
    name: "Germane Fernandez",
    email: "pede.et@yahoo.couk",
    address: "P.O. Box 693, 6291 Tempor Street",
    country: "Pakistan",
    date: "Apr 10, 2023",
  },
];

export default data;
